### ISSUE TITLE
Unable to populate selection lists

### ISSUE THREAD

**Issue by sbt-sb** [hlapp/node-red-contrib-wirelesstag#11]
Not sure if I'm missing something or it's just not working.

I'm able to get the "A" node to return information to the debug panel as it rolls in, but the "S" node keeps giving the same error message:

Unable to populate selection lists (404 - Not Found):
Cannot GET /admin/wirelesstag/<REDACTED>/tagmanagers

This is of course after deploying the node and having it pointing to the same (and only) API config that seems to be working for the "A" node.  Am I missing some important detail?  Thanks.

**Comment by hlapp** [comment]
Can you confirm which version you are running?

**Comment by sbt-sb** [comment]
node-red-contrib-wirelesstag = v0.2.2
nodejs = v6.11.0
node-red = v0.17.3

Just updated everything today, thinking that things weren't working because I was a little out of date on things.

**Comment by hlapp** [comment]
There should be the nodeID of the config node between the two consecutive slashes in `/admin/wirelesstag//tagmanagers`. That's pulled from the selector of the config node. If that's empty string, it normally means that the config node hasn't been deployed yet. Are you sure the config node has been deployed at the time you try to open the selector? For example, did you redeploy everything rather than just the changed nodes? When you restart Node-RED from scratch (assuming you saved the flow), do you get the same error? Is the config node configured for all flows and/or are the "a" and the "s" node in different flows than the config node might be?

I'm running 0.16.x. It's not impossible that Node-RED changed how it sets the config node selector values from 0.16 to 0.17, and that that's the reason. I would hope that's not the case.

**Comment by sbt-sb** [comment]
Sorry, I removed that info, wasn't sure if it was sensitive or not...

Unable to populate selection lists (404 - Not Found):
Cannot GET /admin/wirelesstag/61338ea0.328f/tagmanagers

But to answer your question, yes, everything fully deployed when I attempt to populate the lists.

Also, same behavior after a full restart of server.

Config node configured for all flows, and both the "a" and "s" nodes are in the same flow, as I just got the sensors today and just starting to try to get things setup, so just the most basic flow you can make at this point.  

[inject]--[s-node]--[debug] = Can't populate lists.
[inject]--[a-node]--[debug] = Seems to be working fine.

I was getting the same behavior in 16.x, which is why I upgraded everything to the latest, but still not populating the lists.

The "A" node is spitting out all kinds of valid information, but looks like it would be a lot of extra steps to parse it all out for each sensor.

Thanks.

**Comment by hlapp** [comment]
The nodeID is local, not global (it's a hash), so I don't think it's sensitive. I've shuffled it nonetheless 😄 

I have an idea what's happening. Have you set `httpAdminRoot` in your `settings.js` to `/admin`?

The URL path for the custom HTTP endpoints is generated relative to that of the UI so that the authentication cookie is passed through, but the config node serves those endpoints from the path for the Node-RED nodes.

It seems I need to put that on the admin path instead, even though I wanted to avoid that.

**Comment by hlapp** [comment]
BTW you can check that hypothesis by `curl`ing the URL that gives the 404 on the machine that runs your Node-RED. Replace `/admin` with either nothing, or with the root path you set for `httpNodeRoot` in `settings.js`. If you secured the UI with authentication, you should at least get an auth error, and not a 404.

**Comment by sbt-sb** [comment]
> Have you set httpAdminRoot in your settings.js to /admin?

Yes.

> If you secured the UI with authentication, you should at least get an auth error, and not a 404.

I did secure the UI with authentication, so I tried this:
curl http://localhost:1880/wirelesstag/61338ea0.328f/tagmanagers

And it comes back with: Unauthorized

I also tried:
curl -v http://localhost:1880/admin/wirelesstag/61338ea0.328f/tagmanagers

And got the 404 error.  So if I did all that right, it looks like you're right about your hypothesis.

**Comment by sbt-sb** [comment]
Sorry, I'm a bit of a noob to github protocol here.  Not seeing the new version available from the manage palette section yet, but I did apply the fix manually to wirelesstag-config.js and it's working now.  Very nice.

Thank you so much for the quick fix.

**Comment by hlapp** [comment]
I just pushed a new release to npm, so if you npm update, you should be pulling in the v0.2.3 release. (For the record, I also pushed a v0.1.3 bugfix release to the v0.1.x series, if anyone reads this who uses that still.)

**Comment by hlapp** [comment]
And BTW the issue would have closed automatically when the pull request is merged, because I referenced it in a specific way in the commit message ("_Fixes #11_").

Thanks for your report and working with me on debugging the issue! 👍
